### ISSUE TITLE
feat: Serverless DynamoDB on local

### ISSUE THREAD

**Issue by PricelessCode** [kookmin-sw/capstone-2023-05#15]
체크리스트 만들기

**Comment by PricelessCode** [comment]
@ChangHoon-Sung 혹시 해당 코드가 특별한 동작을 하는게 아니면 지워도 되나요?
찾아보니 CLI 관련 모듈인 것 같은데 의도된 추가인가요?

https://github.com/kookmin-sw/capstone-2023-05/blob/c5795fee43c4650c7b6aa80bb2a0794881e8bf9f/backend/functions/handler.py#L11

**Comment by ChangHoon-Sung** [comment]
> @ChangHoon-Sung 혹시 해당 코드가 특별한 동작을 하는게 아니면 지워도 되나요?
> 
> 찾아보니 CLI 관련 모듈인 것 같은데 의도된 추가인가요?
> 
> 
> 
> https://github.com/kookmin-sw/capstone-2023-05/blob/c5795fee43c4650c7b6aa80bb2a0794881e8bf9f/backend/functions/handler.py#L11

requirements.txt 작성 및 import 정상 동작 여부 확인을 위해 임의로 추가한 내용입니다. 별로 중요한 내용은 아닙니다. 지우셔도 상관없어요.

**Comment by PricelessCode** [comment]
@ChangHoon-Sung 

혹시 시간나시면 여기 2단계까지 환경에서 해보실 수 있을까요?
Document대로 `sls dynamodb install` 과 더불어 여러가지 옵션을 바꾸어 로컬 배포를 하는데 자꾸 아래 에러가 뜨네요. 

혹시 다른 라이브러리나 다른 방법을 써볼까요
```
Error getting DynamoDb local latest tar.gz location undefined: 403
    at ClientRequest.<anonymous> (/home/seungho/Desktop/CS/capstone-2023-05/backend/node_modules/dynamodb-localhost/dynamodb/installer.js:29:15)
```

**Comment by PricelessCode** [comment]
로컬에 적용하는 것이 번거롭고 시간의 문제로 Local testing 부분을 생략하고 AWS에 바로 DynamoDB를 배포하여 연결하기로 했습니다.
이후에 필요하면 이슈 재오픈하도록 하겠습니다.
