### ISSUE TITLE
feat: Lobby

### ISSUE THREAD

**Issue by ChangHoon-Sung** [kookmin-sw/capstone-2023-05#5]
서비스 접속 시 가장 먼저 마주하게 되는 대문 페이지를 개발한다.

디자인 참조: [Figma UI](https://www.figma.com/file/7J3bAPykId2QTJolrgFpa6/Naruhodoo-UI?t=UA13Siz7kbDUpZbD-6)

구성 요소
- 상단 메뉴 바 제공
  - 홈페이지 로고
  - 방 만들기 버튼
  - 로그인/마이페이지 버튼
- 그리드 형식 게임 방 리스트

단계
- [ ] JS Study
    - [ ] MDN JS 문서
    - [ ] Youtube 클론코딩
    - [ ] React
- [x] 상단 메뉴 바 구성
- [ ] 그리드 형식 게임 방 리스트
- [x] 페이지 링크 이동
- [ ] 로그인 기능
- [ ] UI 고도화

이외 수정/변경 시, 위 이슈 메세지를 수정한다.

**Comment by 0gyun** [comment]
- [ ] JS Study
- [ ] 상단 메뉴 바 구성
- [ ] 그리드 형식 게임 방 리스트
- [ ] 페이지 링크 이동
- [ ] 로그인 기능
- [ ] UI 고도화

**Comment by ChangHoon-Sung** [comment]
#80 close this issue.
