### ISSUE TITLE
Update: Modify Opinion table PK

### ISSUE THREAD

**Issue by Binsk-dev** [kookmin-sw/capstone-2023-05#55]
현재 LIKE 기능을 구현 중인데 구현하면서 문득 예전에 논의되었던 부분인데 구현하면서 문제가 되는 부분이 생겨 이슈를 남깁니다.

현재 **Opinion** 테이블의 PK로 총 4가지 필드를 복합키로 사용 중인데 여기서 `timestamp` 필드를 일반 Column으로 변경, `order` 라는 새로운 필드를 정의해 기존의 `timestamp` 필드 자리를 대체하고자 합니다. 

이유는 PK를 정수로 가져가면 깔끔해 보이는 반면 시간 값을 PK로 사용하자니 추후에 검색 쿼리를 다루는 상황이거나 다른 기능을 개발하면서 어색해 보이는 경우가 많아 보입니다.

본 이슈는 #53 가 해결되는대로 수정해서 PR을 만들 예정입니다.
@PricelessCode @Jaewook-Lee

**Comment by Binsk-dev** [comment]
위에서 설명하지 않았는데 **Opinion** 테이블의 변경에 따라 <ins>기존의 **Opinion**과 관련된 기능들도 사이드 이펙트가 생길 겁니다</ins>. 특히 의견 보내기 기능을 구현한 @Jaewook-Lee 님의 경우 본 이슈에서 파생되는 DDL 스크립트 수정 PR이 완료되면 바로 수정하셔야 할 겁니다.

**Comment by PricelessCode** [comment]
#53 Merge 완료했습니다!
좋은 의견 같습니다. 시간이 PK로 들어가면 쿼리가 조금 힘들겠네요!

해당 PR 날려주시면 바로 Approve 하겠습니다!
