### ISSUE TITLE
feat: Provide temporary credential with AWS Cognito Identity Pool

### ISSUE THREAD

**Issue by ChangHoon-Sung** [kookmin-sw/capstone-2023-05#7]
서비스의 오남용을 방지하고, 적법한 인증 및 인가를 거친 사용자만 서비스의 기능을 요청 및 접근할 수 있도록 AWS Cognito User Pool 인증 정보를 기반으로 temporary credential을 제공하는 로직을 검증한다.

예상 검증 시나리오

1. AWS Cognito User Pool 인증을 받은 사용자만 접근할 수 있는 임의의 서비스 생성 (Lambda, API Gateway 등)
2. demo 페이지에서 로그인 없이 서비스 요청
3. 접근 실패 확인
4. demo 페이지에서 로그인 후 서비스 요청
5. 접근 성공 확인

**Comment by Jaewook-Lee** [comment]
필수 기능 구현에 집중하느라 구현하지 못 함
