### ISSUE TITLE
feat: ERD

### ISSUE THREAD

**Issue by ChangHoon-Sung** [kookmin-sw/capstone-2023-05#9]
데이터 모델을 정의하고, 각 데이터 모델의 관계를 보여주는 ERD를 그린다.

- [x] SqlDBM을 활용한 RDB 형식 ERD
- [x] Access pattern(use case) 완성

**Comment by Binsk-dev** [comment]
일단 ERD 완성했고 관련 내용은 깃허브에 남겼으니 확인해보고 의문점이나 이상한 점은 노션 코멘트로 남겨주세요~ 
그럼 저는 힘들어서 사라지겠습니다🫠

**Comment by ChangHoon-Sung** [comment]
넴 노션에서 리뷰 진행 중이고, NoSQL 관련 툴로 ERD 다시 작성 후 리뷰 완료되면 이쪽 이슈 닫아주세용

**Comment by Binsk-dev** [comment]
데이터 모델링은 다음과 같이 이슈를 마무리 합니다.
1. NoSQL 베이스 모델링은 현재 상황에서 크게 느끼지 못하기 때문에 중단합니다.
2. 기존의 RDB 기준 데이터 모델을 백업용으로 사용합니다.
3. 게임 상에서 진행되는 데이터 관리는 Redis가 실시간으로 관리합니다.
